package com.metageek.ssdh.account.model;

import java.util.Set;

import javax.validation.ConstraintViolation;
import javax.validation.Validation;
import javax.validation.Validator;
import javax.validation.ValidatorFactory;

import org.junit.BeforeClass;
import org.junit.Test;

import junit.framework.TestCase;

public class ProfileTest extends TestCase {

	private static Validator validator;
	
	@BeforeClass
    public void setUp() {
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        validator = factory.getValidator();
    }
	
	@Test
	public void test_type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertNotNull(Profile.class);
	}

	@Test
	public void test_instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		Profile target = new Profile(null, null, null);
		assertNotNull(target);
	}

	@Test
	public void test_validateNullProfile() throws Exception {
		// Instantiate Credential with null test data and validate
		// Expect failure
		Profile ua = new Profile(null, null, null);
		
		Set<ConstraintViolation<Profile>> constraintViolations = validator.validate( ua );

	    assertEquals(3, constraintViolations.size() );
	    assertEquals("must not be null", constraintViolations.iterator().next().getMessage() );
	    assertEquals("must not be null", constraintViolations.iterator().next().getMessage() );
	}

	@Test
	public void test_validateValidAccount() throws Exception {
		// Instantiate Credential with null test data and validate
		// Expect failure
		Profile ua = new Profile("Neil", "Armstrong", "neil.armstrong@nasa.gov");
		
		Set<ConstraintViolation<Profile>> constraintViolations = validator.validate( ua );

	    assertEquals(0, constraintViolations.size());
	}
}
