package com.metageek.ssdh.account.model;

import java.util.Set;

import javax.validation.ConstraintViolation;
import javax.validation.Validation;
import javax.validation.Validator;
import javax.validation.ValidatorFactory;

import org.junit.BeforeClass;
import org.junit.Test;

import junit.framework.TestCase;

public class UserAccountTest extends TestCase {

	private static Validator validator;
	
	@BeforeClass
    public void setUp() {
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        validator = factory.getValidator();
    }
	
	@Test
	public void test_type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertNotNull(UserAccount.class);
	}

	@Test
	public void test_instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		UserAccount target = new UserAccount(null, null, null, null);
		assertNotNull(target);
	}

	@Test
	public void test_validateNullAccount() throws Exception {
		// Instantiate UserCredential with null test data and validate
		// Expect failure
		UserAccount ua = new UserAccount(null, null, null, null);
		
		Set<ConstraintViolation<UserAccount>> constraintViolations = validator.validate( ua );

	    assertEquals(4, constraintViolations.size() );
	    assertEquals("must not be null", constraintViolations.iterator().next().getMessage() );
	    assertEquals("must not be null", constraintViolations.iterator().next().getMessage() );
	}

	@Test
	public void test_validateValidAccount() throws Exception {
		// Instantiate UserCredential with null test data and validate
		// Expect failure
		UserCredential uc = new UserCredential("starman", "UCVJhUaz22V02MfCNN#a!*");
		UserAccount ua = new UserAccount("Neil", "Armstrong", "neil.armstrong@nasa.gov", uc);
		
		Set<ConstraintViolation<UserAccount>> constraintViolations = validator.validate( ua );

	    assertEquals(0, constraintViolations.size());
	}
}
