AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless SSDH Account API - com.metageek.ssdh::account
Resources:
  SSDHAccountEndpoints:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.metageek.ssdh.account.service.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/account-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        PingResource:
          Type: Api
          Properties:
            Path: /ping
            Method: GET
        AccountResource:
          Type: Api
          Properties:
            Path: /account
            Method: any
        AuthenticationResource:
          Type: Api
          Properties:
            Path: /authentication
            Method: any

Outputs:
  SSDHApiPing:
    Description: SSDH Ping endpoint
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: PingApi
  SSDHApiAccount:
    Description: SSDH Account endpoint
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/account'
    Export:
      Name: AccountApi
  SSDHApi:
    Description: SSDH Account endpoint
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/authentication'
    Export:
      Name: AuthenticationApi
