AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless SSDH Account API - com.metageek.ssdh::account
Resources:
  SSDHAccountEndpoints:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.metageek.ssdh.account.service.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/account-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SSDHAccountApi:
    Description: SSDH Account endpoints
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: AccountApi
