package com.metageek.ssdh.account.util;

import static java.nio.charset.StandardCharsets.UTF_8;

import java.nio.charset.Charset;

import junit.framework.TestCase;

public class PasswordUtilTest extends TestCase {

	public void test_type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertNotNull(PasswordUtil.class);
	}

	public void test_instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		PasswordUtil target = new PasswordUtil();
		assertNotNull(target);
	}

	public void test_hash_A$charArray$Charset() throws Exception {
		// TODO auto-generated by JUnit Helper.
		String passwordString = "LXfd6Ji7YCZHTW.pv/xk";
		char[] password = passwordString.toCharArray();
		Charset charset = UTF_8;
		String hash = PasswordUtil.hash(password, charset);
		assertNotNull(hash);
	}

	public void test_verify_A$String$charArray$Charset() throws Exception {
		// TODO auto-generated by JUnit Helper.
		String hash = "$argon2i$v=19$m=128000,t=40,p=4$acLKPAx0gii/Lj8+4QuVdQ$TwUD/4T6valWhECX3fQjjRV8RqUoJM0jWMCTdWy0dN8";
		String passwordString = "LXfd6Ji7YCZHTW.pv/xk";
		char[] password = passwordString.toCharArray();
		Charset charset = UTF_8;
		boolean actual = PasswordUtil.verify(hash, password, charset);
		boolean expected = true;
		assertEquals(expected, actual);
	}

}
